# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cache_machine}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Balthrop"]
  s.date = %q{2011-03-21}
  s.description = %q{A Rails engine for quick, convenient caching.}
  s.email = %q{code@justinbalthrop.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION.yml"
  ]
  s.homepage = %q{http://github.com/ninjudd/cache_machine}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails engine for quick, convenient caching.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<memcache>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<cache_version>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<record_cache>, [">= 0.9.12"])
      s.add_runtime_dependency(%q<method_cache>, [">= 0.6.3"])
    else
      s.add_dependency(%q<memcache>, [">= 1.0.0"])
      s.add_dependency(%q<cache_version>, [">= 0.9.4"])
      s.add_dependency(%q<record_cache>, [">= 0.9.12"])
      s.add_dependency(%q<method_cache>, [">= 0.6.3"])
    end
  else
    s.add_dependency(%q<memcache>, [">= 1.0.0"])
    s.add_dependency(%q<cache_version>, [">= 0.9.4"])
    s.add_dependency(%q<record_cache>, [">= 0.9.12"])
    s.add_dependency(%q<method_cache>, [">= 0.6.3"])
  end
end

